// src/components/TodoItem.vue
<script setup lang='ts'>
    import type { Todo } from '../types'

    defineProps<{
        todo: Todo
    }>()

    const emit = defineEmits<{
        (e: 'toggle-todo', id: number): void
        (e: 'delete-todo', id: number): void
    }>()
</script>

<template>
    <li 
      :class='{ completed: todo.completed }'>
        
      <input type='checkbox' 
        :checked='todo.completed' 
        @change="emit('toggle-todo', todo.id)" />
        {{ todo.title }}
      
        <button @click="emit('delete-todo', todo.id)">×</button>
      
      </li>
</template>

<style>
  .completed {
    font-weight: bold;
  }
</style>

// src/components/TodoItem.tsx
import type { Todo } from '../types'

interface TodoItemProps {
    todo: Todo
    onToggleTodo: (id: number) => void
    onDeleteTodo: (id: number) => void
 }

 function TodoItem({ todo, onToggleTodo, onDeleteTodo }: TodoItemProps) {
    return (
        <li className={todo.completed ? 'completed' : ''}>
            <input
            type='checkbox'
            checked={todo.completed}
            onChange={() => onToggleTodo(todo.id)}
            />
            { todo.title }
            <button onClick={() => onDeleteTodo(todo.id)}>Delete</button>
        </li>
    )  
 }
